app = "thelaaw-evolution-laaw"
primary_region = "lhr"

[build]
image = "atendai/evolution-api:v2.2.3"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 1

[[vm]]
size = "shared-cpu-1x"
memory = "512mb"

[env]
  PORT = "8080"
  SERVER_URL = "https://thelaaw-evolution-laaw.fly.dev"
  AUTHENTICATION_TYPE = "apikey"
  AUTHENTICATION_API_KEY = "thelaaw_secret_key"
  AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES = "true"
  DATABASE_ENABLED = "true"
  DATABASE_PROVIDER = "postgresql"
  DATABASE_CONNECTION_URI = "postgresql://neondb_owner:npg_iOTH5GJyK2jk@ep-cool-water-amyd2tzf.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require"
  DATABASE_CONNECTION_CLIENT_NAME = "evolution_v2"
  WEBHOOK_GLOBAL_ENABLED = "true"
  WEBHOOK_GLOBAL_URL = "https://thelaaw-1.onrender.com/webhook/whatsapp"
  WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS = "false"
  WEBHOOK_EVENTS_MESSAGES_UPSERT = "true"
  WEBHOOK_EVENTS_MESSAGES_UPDATE = "true"
  WEBHOOK_EVENTS_SEND_MESSAGE = "true"
  WEBHOOK_EVENTS_CONNECTION_UPDATE = "true"
  CACHE_REDIS_ENABLED = "false"
  CACHE_LOCAL_ENABLED = "true"
  LOG_LEVEL = "ERROR"
